Repository ahachulTeam/ahhachul_backend, pull requests merged in 2024-11, with the labels that each got.

#241 구글 로그인 api에서 DTO에 없는 필드를 response해도 에러가 발생하지 않도록 수정
  ahachul_backend/src/main/kotlin/backend/team/ahachul_backend/common/dto/GoogleUserInfoDto.kt
Labels: 🐛 Bug

#251 ✨ 첫 로그인 시 닉네임 입력 기능 동작 변경 (#250)
  core/src/main/kotlin/backend/team/ahachul_backend/api/member/domain/entity/MemberEntity.kt
Labels: 🕹 Feature

#259 ♻️ 유실물 상세조회 리팩토링 (#237)
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/dto/GetLostPostDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/application/service/LostPostService.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/LostPostControllerDocsTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/lost/application/service/LostPostServiceTest.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/lost/domain/entity/LostPostEntity.kt
Labels: 🛠 Refactor

#260 :recycle: 유실물 생성, 업데이트, 삭제 리팩토링
  application/src/docs/asciidoc/lost/posts.adoc
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/dto/CreateLostPostDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/dto/UpdateLostPostDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/application/service/LostPostService.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/LostPostControllerDocsTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/lost/application/service/LostPostServiceTest.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/lost/application/command/in/CreateLostPostCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/lost/application/command/in/UpdateLostPostCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/lost/domain/entity/LostPostEntity.kt
Labels: 🛠 Refactor

#262 🐛 애플 로그인 시, p8 키 파일 못찾는 에러 수정 (#261)
  application/src/main/kotlin/backend/team/ahachul_backend/common/client/impl/AppleMemberClientImpl.kt
Labels: 🐛 Bug

#267 :bug: SNS 로그인 시, 회원테이블 INSERT 오류 발생 수정 (#266)
  core/src/main/resources/db/migration/V202411181200__update_member_nickname_null.sql
Labels: 🐛 Bug

#270 :bug: 애플에서 이메일 값을 주지 않아 NULL 처리 (#269)
  core/src/main/kotlin/backend/team/ahachul_backend/api/member/domain/entity/MemberEntity.kt
  core/src/main/kotlin/backend/team/ahachul_backend/common/dto/AppleUserInfoDto.kt
Labels: 🐛 Bug

#274 :recycle: allow origin pattern 변경 app-dev에서 app.dev로 변경 (#273)
  application/src/main/kotlin/backend/team/ahachul_backend/common/config/InterceptorConfig.kt
Labels: 🛠 Refactor
