Repository ahachulTeam/ahhachul_backend, pull requests merged in 2024-12, with the labels that each got.

#282 ✨ 유실물 댓글 조회 구현
  application/src/main/kotlin/backend/team/ahachul_backend/api/comment/application/service/CommentService.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/adapter/web/in/CommunityPostCommentController.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/LostPostCommentController.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/comment/application/service/CommentServiceTest.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/comment/adapter/web/out/CommentPersistence.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/comment/adapter/web/out/CommentRepository.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/comment/application/command/GetCommentsCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/comment/application/port/out/CommentReader.kt
Labels: 🕹 Feature

#285 ♻️ 커뮤니티 게시글 조회 리팩토링
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/adapter/web/in/CommunityPostController.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/adapter/web/in/CommunityPostLikeController.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/adapter/web/in/dto/CreateCommunityPostDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/adapter/web/in/dto/DeleteCommunityPostDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/adapter/web/in/dto/SearchCommunityPostDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/adapter/web/in/dto/UpdateCommunityPostDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/application/port/in/CommunityPostUseCase.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/application/service/CommunityPostService.kt
  application/src/test/kotlin/backend/team/ahachul_backend/admin/application/service/AdminServiceTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/community/adapter/web/in/CommunityPostControllerDocsTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/community/application/service/CommunityPostServiceTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/report/application/service/CommunityPostReportServiceTest.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/adapter/web/out/CommunityPostPersistence.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/adapter/web/out/CustomCommunityPostRepository.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/application/command/DeleteCommunityPostCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/application/command/GetCommunityPostCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/application/command/SearchCommunityPostCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/application/command/in/CreateCommunityPostCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/application/command/in/DeleteCommunityPostCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/application/command/in/GetCommunityPostCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/application/command/in/SearchCommunityPostCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/application/command/in/UpdateCommunityPostCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/application/command/out/GetSliceCommunityPostCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/application/port/out/CommunityPostReader.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/domain/entity/CommunityPostEntity.kt
Labels: 🛠 Refactor

#288 ✨ 댓글에 isPrivate 필드 추가
  application/src/main/kotlin/backend/team/ahachul_backend/api/comment/adapter/web/in/dto/GetCommentsDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/comment/application/service/CommentService.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/community/adapter/web/in/CommunityPostCommentControllerDocsTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/LostPostCommentControllerDocsTest.kt
Labels: 🕹 Feature

#292 :bug: 유실물 commentCnt 적용 (#290)
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/dto/GetLostPostDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/dto/SearchLostPostsDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/application/service/LostPostService.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/comment/adapter/web/out/CommentPersistence.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/comment/adapter/web/out/CommentRepository.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/comment/application/port/out/CommentReader.kt
Labels: 🐛 Bug

#294 :recycle: 유실물 상세 조회 시, lostType 필드 추가 (#293)
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/dto/GetLostPostDto.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/LostPostControllerDocsTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/lost/application/service/LostPostServiceTest.kt
Labels: 🛠 Refactor

#302 :bug: 유실물 업데이트 REST DOCS 매핑 오류 수정 (#301)
  application/src/docs/asciidoc/lost/posts.adoc
  application/src/test/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/LostPostControllerDocsTest.kt
Labels: 🐛 Bug

#296 ✨ 유실물 상태 업데이트 API 기능 추가
  application/src/docs/asciidoc/lost/posts.adoc
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/LostPostController.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/dto/UpdateLostPostStatusDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/application/port/in/LostPostUseCase.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/application/service/LostPostService.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/LostPostControllerDocsTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/lost/application/service/LostPostServiceTest.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/lost/application/command/in/UpdateLostPostStatusCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/lost/domain/entity/LostPostEntity.kt
Labels: 🕹 Feature

#304 🐛 비밀 댓글을 볼 수 없는 사용자 에게는 내용을 빈 값으로 응답하도록 수정
  application/src/main/kotlin/backend/team/ahachul_backend/api/comment/application/service/CommentService.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/adapter/web/in/CommunityPostCommentController.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/adapter/web/in/LostPostCommentController.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/comment/application/service/CommentServiceTest.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/comment/domain/entity/CommentEntity.kt
Labels: 🐛 Bug
