Repository ahachulTeam/ahhachul_backend, pull requests merged in 2025-02, with the labels that each got.

#320 ✨ 사용자 목록 조회 API (#319)
  application/src/docs/asciidoc/member/error.adoc
  application/src/docs/asciidoc/member/members.adoc
  application/src/main/kotlin/backend/team/ahachul_backend/api/member/adapter/web/in/MemberController.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/member/adapter/web/in/dto/SearchMemberDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/member/application/port/in/MemberUseCase.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/member/application/service/MemberService.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/member/adapter/web/in/MemberControllerDocsTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/member/application/service/MemberServiceTest.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/member/adapter/web/out/MemberPersistence.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/member/adapter/web/out/MemberRepository.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/member/application/command/SearchMemberCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/member/application/port/out/MemberReader.kt
  core/src/main/kotlin/backend/team/ahachul_backend/common/response/ResponseCode.kt
Labels: 🕹 Feature

#325 :recycle: 로그아웃 테스트 코드 에러 코드 수정 (#319)
  application/src/test/kotlin/backend/team/ahachul_backend/api/member/adapter/web/in/AuthLogoutControllerTest.kt
Labels: 🐛 Bug

#327 :bug: Github Actions artifact V4 업그레이드 (#326)
  .github/workflows/dev-api-deploy.yml
  .github/workflows/dev-batch-deploy.yml
Labels: 🏗 Infra, 🐛 Bug

#324 🐛 커뮤니티 글 작성/수정 API 버그 수정
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/adapter/web/in/CommunityPostController.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/adapter/web/in/dto/CreateCommunityPostDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/adapter/web/in/dto/UpdateCommunityPostDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/application/service/CommunityPostService.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/application/command/in/CreateCommunityPostCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/application/command/in/UpdateCommunityPostCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/community/domain/model/CommunityCategoryType.kt
Labels: 🐛 Bug

#333 :bug: 코멘트 테이블의 민원 ID 컬럼 추가 (#332)
  core/src/main/resources/db/migration/V202502031200__add_comment_complaint_column.sql
Labels: 🐛 Bug

#336 :recycle: 민원 생성 subwayLineId 필드명 변경 (#335)
  application/src/main/kotlin/backend/team/ahachul_backend/api/complaint/adapter/web/in/dto/CreateComplaintPostDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/complaint/application/service/ComplaintPostService.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/complaint/adapter/web/in/ComplaintPostControllerDocsTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/complaint/application/service/ComplaintPostServiceTest.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/complaint/application/command/in/CreateComplaintPostCommand.kt
Labels: 🛠 Refactor

#340 ♻️ 역 즐겨찾기 우선순위 적용 (#339)
  application/src/main/kotlin/backend/team/ahachul_backend/api/member/adapter/web/in/MemberController.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/member/adapter/web/in/dto/BookmarkStationDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/member/adapter/web/in/dto/GetBookmarkStationDto.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/member/application/port/in/MemberUseCase.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/member/application/service/MemberService.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/member/adapter/web/in/MemberControllerDocsTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/member/application/service/MemberServiceTest.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/member/adapter/web/out/MemberStationPersistence.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/member/application/command/BookmarkStationCommand.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/member/application/command/BookmarkStationCommands.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/member/application/port/out/MemberStationWriter.kt
  core/src/main/kotlin/backend/team/ahachul_backend/api/member/domain/entity/MemberStationEntity.kt
  core/src/main/kotlin/backend/team/ahachul_backend/common/response/ResponseCode.kt
  core/src/main/resources/db/migration/V202502191200__add_label_column.sql
Labels: 🛠 Refactor

#299 RequestUtils key값을 enum class로 받도록 수정
  application/src/main/kotlin/backend/team/ahachul_backend/api/comment/application/service/CommentLikeService.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/comment/application/service/CommentService.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/application/service/CommunityPostLikeService.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/community/application/service/CommunityPostService.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/complaint/application/service/ComplaintPostService.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/lost/application/service/LostPostService.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/member/application/service/MemberService.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/report/application/service/CommunityPostReportService.kt
  application/src/main/kotlin/backend/team/ahachul_backend/api/report/application/service/LostPostReportService.kt
  application/src/main/kotlin/backend/team/ahachul_backend/common/interceptor/AuthenticationInterceptor.kt
  application/src/test/kotlin/backend/team/ahachul_backend/admin/application/service/AdminServiceTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/comment/application/service/CommentLikeServiceTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/comment/application/service/CommentServiceTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/community/application/service/CommunityPostServiceTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/complaint/application/service/ComplaintPostServiceTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/lost/application/service/LostPostServiceTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/member/application/service/MemberServiceTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/report/application/service/CommunityPostReportServiceTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/report/application/service/LostPostReportServiceTest.kt
  application/src/test/kotlin/backend/team/ahachul_backend/api/train/application/service/TrainServiceTest.kt
  core/src/main/kotlin/backend/team/ahachul_backend/common/config/JpaConfig.kt
  core/src/main/kotlin/backend/team/ahachul_backend/common/utils/RequestUtils.kt
Labels: 🛠 Refactor
